"""create initial schema

Revision ID: 7768cfd3a397
Revises:
Create Date: 2026-08-07 02:34:59.764560

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7768cfd3a397"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "authentication_identities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(provider = 'password' AND password_hash IS NOT NULL) OR "
            "(provider = 'google' AND password_hash IS NULL)",
            name="ck_authentication_identities_password_hash",
        ),
        sa.CheckConstraint(
            "provider IN ('password', 'google')", name="ck_authentication_identities_provider"
        ),
        sa.CheckConstraint(
            "normalized_email = lower(normalized_email)",
            name="ck_authentication_identities_normalized_email",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_authentication_identities_provider_subject"
        ),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_authentication_identities_user_provider"
        ),
    )
    op.create_index(
        "ix_authentication_identities_user_id",
        "authentication_identities",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_authentication_identities_password_email",
        "authentication_identities",
        ["normalized_email"],
        unique=True,
        postgresql_where=sa.text("provider = 'password'"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False
        ),
        sa.Column("schema_version", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("profile_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("workout_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nutrition_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'archived' AND archived_at IS NOT NULL) OR "
            "(status <> 'archived' AND archived_at IS NULL)",
            name="ck_plans_archived_at",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(nutrition_plan) = 'object'", name="ck_plans_nutrition_plan_object"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(profile_snapshot) = 'object'", name="ck_plans_profile_snapshot_object"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(workout_plan) = 'object'", name="ck_plans_workout_plan_object"
        ),
        sa.CheckConstraint("status IN ('inactive', 'active', 'archived')", name="ck_plans_status"),
        sa.CheckConstraint("schema_version > 0", name="ck_plans_schema_version"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_plans_user_id", "plans", ["user_id"], unique=False)
    op.create_index(
        "uq_plans_one_active_per_user",
        "plans",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("fitness_goal", sa.String(length=30), nullable=False),
        sa.Column("experience_level", sa.String(length=20), nullable=False),
        sa.Column("days_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("session_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "equipment",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "dietary_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "wellness_constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "experience_level IN ('beginner', 'intermediate', 'advanced')",
            name="ck_profiles_experience_level",
        ),
        sa.CheckConstraint(
            "fitness_goal IN "
            "('general_fitness', 'strength', 'muscle_gain', 'endurance', 'weight_management')",
            name="ck_profiles_fitness_goal",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dietary_preferences) = 'array'",
            name="ck_profiles_dietary_preferences_array",
        ),
        sa.CheckConstraint("jsonb_typeof(equipment) = 'array'", name="ck_profiles_equipment_array"),
        sa.CheckConstraint(
            "jsonb_typeof(wellness_constraints) = 'array'",
            name="ck_profiles_wellness_constraints_array",
        ),
        sa.CheckConstraint("days_per_week BETWEEN 1 AND 7", name="ck_profiles_days_per_week"),
        sa.CheckConstraint(
            "session_minutes BETWEEN 1 AND 1440", name="ck_profiles_session_minutes"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    op.drop_index(
        "uq_plans_one_active_per_user",
        table_name="plans",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_plans_user_id", table_name="plans")
    op.drop_table("plans")
    op.drop_index(
        "uq_authentication_identities_password_email",
        table_name="authentication_identities",
        postgresql_where=sa.text("provider = 'password'"),
    )
    op.drop_index("ix_authentication_identities_user_id", table_name="authentication_identities")
    op.drop_table("authentication_identities")
    op.drop_table("users")
    # ### end Alembic commands ###
